### ISSUE TITLE
Potential Problem with Voxel Sign

### ISSUE THREAD

**Issue by mbowren** [dorianps/LESYMAP#11]
Hi Dr. Pustina,

I am using the newest version of lesymap's SCCAN routine, which searches for both positive and negative correlations with the behavior. I have a large patient sample in which some patients have left-sided damage and others have right-sided damage. I am using the SCCAN method to find the neural correlates of a lateralized behavior among the entire sample. For example, I have a language factor generated through factor analysis (language is classically associated with the left-hemisphere). The program produces a stat_img.nii.gz file that shows negative correlations with damage to left-hemisphere regions (as you would expect), but the _same map_ also shows **positive** correlations with damage to **right-hemisphere regions**. One interpretation is that damage to right-hemisphere regions improves language ability. However, this obviously seems like an unlikely explanation. The same thing happens for visuospatial abilities; this variable should be negatively associated with right-hemisphere damage, but SCCAN produces a map that also includes positive associations with left-hemisphere damage. 

I think that what may be happening is that having both positive and negative voxel weights helps SCCAN to **maximize** the correlation between voxel values and behavioral scores in this situation. This is because having unilateral right-sided damage, for example, means that you by definition do not have left-sided damage.

Do you have any thoughts about the best way to overcome this? I was thinking that it would be useful to be able to restrict SCCAN to finding only negative associations (that is, we can assume subtractivity after brain lesions). **However, that is NOT what the old version of SCCAN did (i.e. setting directionalSCCAN to FALSE will not fix this problem).** The old version will sometimes output a result that shows only voxels with a positive association if the positive association is stronger than the negative (which happened to me with the language analysis, where it produces a result with only right-sided findings). But because the old version did not tell you the direction of the correlation, you might be misled. I assume that setting directionalSCCAN to TRUE and then getting rid of the positive voxels afterwards is not appropriate since the entire map was evaluated for statistical significance, not just the negative voxels. So the cross-validation does not apply to only the negative voxels. This makes me think that it would be helpful to limit SCCAN to finding only negative correlations (i.e., cross-validate and produce maps with only negative voxel weights). 

Thank you for your hard work on this program. It does a fantastic job in most cases and has been a valuable contribution to the lesion analysis community. 

Mark Bowren

**Comment by stnava** [comment]
i havent seen a clear statement of the software problem in the above discussion other than what sounds like idiosycratic ( dataset - specific ) issues.  as usual: https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example

regarding forcing negative weights - this assumes a notion of weight directionality which does not exist.  ie note that:

https://www.researchgate.net/post/How_to_determine_the_sign_of_eigenvector

in the case of correlation, this translates to:

Corr( A * (-1) ,   B )  =  corr( A,  B * (-1 )  )

to alter this behavior, one would have to write down a specific mathematical constraint that can be optimized.

the existing constraints in SCCAN are either:

(1)  make eigenvectors sparse but ignore the sign -  this case excludes small weights

(2)  make eigenvectors unsigned - this case keeps the largest magnitude weights regardless of whether they are on the positive or negative side.   remember that we can switch signs arbitrarily due to the above mathematical issue.    

what would your proposed approach be?

to address the original issue that was posted, i would recommend restricting analysis to the left hemisphere.   i.e. use your prior knowledge.  that always helps.

**Comment by dorianps** [comment]
@stnava 

The conceptual problem is that voxel values are anti-correlated between left and right hemispheres, because people have either lesion on the right or lesion on the left. This problem can also extend within one hemisphere, those that have an ischemic event on the anterior branch of the middle cerebral artery don't have it on the posterior branch, and vice versa.

In mass-univariate analysis it is kind of easy to simply explore only one alternative, that is, lesion = worse performance. In SCCAN this is not possible. I was was wondering if it makes sense to add a constraint within SCCAN iterations so that all positive weights are set to zero, thus forcing the identification of sccan components that rely only on negative weights. I am not sure if this makes sense mathematically, but it's the closest thing to the "alternatives" in mass univariate analysis I can think of. Restricting the analysis to one hemisphere may be an ad-hoc solution but is limited only to those functions we know for sure are unilateral; and does not resolve the anti-correlation problem when is happening on the same hemisphere.

Thanks for tipping in.

**Comment by dorianps** [comment]
Mark, did you run ttest with alternative two sided?

Brian's suggestion of having two components is probably the best solution,
but it needs time to implement, figure out the what the two components will
produce, cross validate the good one, etc. For now you can use an ad hoc
solution. Can you share your data with me so I can use them to test the
approach?

I'd also suggest you try SVR to see if the issue of the wrong hemisphere is
present.

**Comment by stnava** [comment]
here is an example of how things work in the scenario you describe:

```
library( ANTsR )
set.seed( 99 )
n = 450
cog1 = rnorm( n )
cog2 = rnorm( n )
idim = c( 30, 60 )
nvox = prod( idim )
maskVox = rep(1,nvox)
maskimg = makeImage( idim, maskVox )
# make a bunch of univariate correlations where pos corrs are stronger
negCog1 = cog1 * (-1) + matrix( rnorm( nvox/2 * n ), nrow=n ) * 2
posCog2 = cog1 + matrix( rnorm( nvox/2 * n ), nrow=n  ) * 0.5
hist( cor( negCog1, cog1 ) )
hist( cor( posCog2, cog1 ) )
joinedMat = cbind( negCog1, posCog2 )
cogs = cbind( cog1, cog2 ) # both cogs, though only 1 is relevant
maskt = thresholdImage(maskimg,1,2)
mydecom <- sparseDecom2( inmatrix=list( joinedMat,  cogs ),
  inmask = list( maskt, NA), smooth = 1.5, cthresh = c(50,0), maxBased=T,
  sparseness=c( 0.33, 0.1 ), nvecs=5, its=5, perms=0, mycoption = 1 )
layout(matrix(c(1:5), 1, 5, byrow = TRUE))
mycorrs = diag(
  cor( joinedMat %*% abs(mydecom$eig1),  cogs %*% abs( mydecom$eig2 )   ))
for ( i in 1:ncol( mydecom$eig1 ) ) {
  temp = makeImage( maskt, abs(mydecom$eig1[,i] ))
  print( paste("Corr", mycorrs[i] ))
  print(
    paste( i, "VoxEvec", paste( range(mydecom$eig1[,i]), collapse=" n/p "  ) ) )
  print(
    paste( i, "CogEvec",paste( mydecom$eig2[,i], collapse=" <=> " ) ) )
  plot( temp* 1e6, doCropping=F )
  print(")-----------------------------------------------(")
  Sys.sleep( 1 )
  }
# by inspecting the above results, you can see that both the positive simulated
# data and the negative are "discovered" - but they exist in different eigenvectors.

```
