### ISSUE TITLE
lesymap.predict() subscript out of bounds

### ISSUE THREAD

**Issue by mbowren** [dorianps/LESYMAP#17]
Hi Dr. Pustina,

I noticed that in the new version of lesymap, lesymap.predict() gives me this error: 

Error in input[[i]] : subscript out of bounds

Thank you for your time!

Mark

**Comment by dorianps** [comment]
Mark, I can't replicate the error using a fresh ANTsR installation from tonight. Note that ANTsR had a number of errors recently due to the independent development of its core (ANTsRCore) and the more specialized functions of ANTsR itself. Those are resolved with the merge that happened today. I advise you run a fresh install of ITKR/ANTsRCore/ANTsR and try again. I am not sure the error you experience is related to those issues, but can't do much if I cant replicate the error.

Here is the code I use to try replicate the error.

```r
library(LESYMAP)
lesydata = file.path(find.package('LESYMAP'),'extdata')
filenames = Sys.glob(file.path(lesydata, 'lesions', 'Subject*.nii.gz'))
behavior = Sys.glob(file.path(lesydata, 'behavior', 'behavior.txt'))
lesions = imageFileNames2ImageList(filenames)
behav = read.table(behavior)$V1 * 1000

train = 1:100
test = 101:131

lsm = lesymap(lesions[train], behav[train], method='sccan', sparseness=0.2, validateSparseness=F)

predbehav = lesymap.predict(lsm, lesions[test])
```

**Comment by dorianps** [comment]
Assuming this is resolved. Please reopen if needed.
