### ISSUE TITLE
LESYMAP Errors - Mask in different Space & antsAverageImages

### ISSUE THREAD

**Issue by haleksonis** [dorianps/LESYMAP#24]
Hello Dorian,

I have been trying to use lesymap for some analysis but have run into some errors that a colleague and I have not been able to figure out. I am hoping that you can help!

The first error I received (attached) stated that the lesion files and mask are in different spaces. However, as far as I can tell, they are in the same space. Even after using 3dresample to be sure that the lesion files and mask are in the same space, I continue to receive this error. Have you encountered this problem before?

Additionally, I tried to run the analysis without my mask file and simply inputed a number into minSubjectPerVoxel and received the attached error. A colleague and I tried to troubleshoot and cannot seem to understand what it may be referring to. Have you encountered this error before?

Thank you!
Best,
Holly
<img width="784" alt="LESYMAP_error2" src="https://user-images.githubusercontent.com/65725032/82576764-116ced00-9b58-11ea-8089-308b40c37d63.png">
<img width="791" alt="LESYMAP_error_mask" src="https://user-images.githubusercontent.com/65725032/82576769-1336b080-9b58-11ea-8cb7-7872aad0d7e9.png">

**Comment by dorianps** [comment]
Hi Holly,

First problem:
Someone reported an issue where very tiny differences in image orientation caused the issue. There is a simple fix I need to make in lesymap to circumvent the issue, but I thought this wasn't a common problem. The workaround until I implement a fix is to copy the headers from an image to your mask, as shown in this thread: https://github.com/ANTsX/ANTsR/issues/301
However, the workaround only makes sense if you are absolutely certain the two images are in the same space by checking something like antsGetOrientations() in ANTsR or PrintHeader in ANTs. You can also load the images in ITKsnap and check the header/orientations. In a normal workflow, this does not happen because the mask is derived from the images themselves. You seem to have computed the mask on your own, maybe with other software, which is a bit concerning that headers truly change (different software treat nifti headers differently).

Second problem:
I need to troubleshoot, looks like a trivial bug caused by some ANTsR change of a function. But to do that properly, I need to know which package versions are you using. Please paste the outputs of `library(LESYMAP) ; sessionInfo()`.

**Comment by dorianps** [comment]
Second problem (update):
The suspect ANTsR function has not changed, you seem to have installed a new LESYMAP version alongside an old ANTsR (10+ months). If that is the case, please update ANTsR to the current version.

**Comment by haleksonis** [comment]
Hi Dorian,

Thank you for your response. We have updated the ANTsR to the current version and are no longer receiving the error. Thank you!


Holly A. Aleksonis
Doctoral Student
Clinical Neuropsychology & Cognitive Neuroscience
Brains & Behavior Fellow
Georgia State University

Lab Website: http://sites.gsu.edu/kinglab/

On May 21, 2020, at 1:45 PM, dorianps <notifications@github.com<mailto:notifications@github.com>> wrote:



Second problem (update):
The suspect ANTsR function has not changed, you seem to have installed a new LESYMAP version alongside an old ANTsR (10+ months). If that is the case, please update ANTsR to the current version.

**Comment by dorianps** [comment]
Holly, please note that you need to specify `minSubjectPerVoxel=2` and not `minSubjectPerVoxel="2"` if you want to threshold by 2 subjects. From what I see in the code, lesymap will misinterpret a character input as a percentage, it needs to be numeric when defining exact number of subjects.
