### ISSUE TITLE
LESYMAP: register to Template WARNING message

### ISSUE THREAD

**Issue by marivas-MRI** [dorianps/LESYMAP#27]
Dear Dorian, 

Before ran the SCCAN analysis I tried to register the binary lesions to the default LESYMAP's template. It seems that all worked fine. However, the following warning message appeared in my terminal: 

WARNING: In /home/miguel/R/x86_64-pc-linux-gnu-library/3.6/ITKR/libs/include/ITK-5.1/itkMultiStartOptimizerv4.hxx, line 186
MultiStartOptimizerv4Template (0x7fad1c037560): An exception occurred in sub-optimization number 0.  If too many of these occur, you may need to set a different set of initial parameters.

WARNING: In /home/miguel/R/x86_64-pc-linux-gnu-library/3.6/ITKR/libs/include/ITK-5.1/itkMultiStartOptimizerv4.hxx, line 186
MultiStartOptimizerv4Template (0x7fad1c037560): An exception occurred in sub-optimization number 1.  If too many of these occur, you may need to set a different set of initial parameters.

WARNING: In /home/miguel/R/x86_64-pc-linux-gnu-library/3.6/ITKR/libs/include/ITK-5.1/itkMultiStartOptimizerv4.hxx, line 186
MultiStartOptimizerv4Template (0x7fad1c037560): An exception occurred in sub-optimization number 2.  If too many of these occur, you may need to set a different set of initial parameters.

Is this relevant?. In that case, how could I fix this issue?

Thanks for your time. 

Best, 

Miguel.

**Comment by dorianps** [comment]
Check the registration by overlaying  the subject MRI image to the template
in itksnap. If that looks ok, there should be no problem. The gyri and
ventricles b should correspond.

I think this is the warning that used to be called "bad det" and was not an
issue.

**Comment by marivas-MRI** [comment]
Thanks for your quick response Dorian. All looks ok in itksnap. Just an additional question, using the SCCAN analysis, it seems that there is a problem with the Header Info of my images. After perform the registration, I used as input the reg_SubjectCode_subLestionTemplate.nii.gz files for the SCCAN analysis. I tried with the following command and this error appeared: 



lesydata = file.path(find.package('LESYMAP'), 'estudio_lesiones')
filenames = Sys.glob(file.path(lesydata, 'lesiones', 'reg_*.nii.gz'))
behavior = "/Users/neucoga/LESYMAP/inst/estudio_lesiones/conducta/beh.txt"

lsm = LESYMAP::lesymap(filenames, behavior, mask = NA, patchinfo = NA, method = "sccan", correctByLesSize = "none", multipleComparison = "fdr", pThreshold = 0.05, flipSign = F, minSubjectPerVoxel = "10%", nperm = 1000, saveDir = '/Users/neucoga/LESYMAP/inst/estudio_lesiones/resultados/', binaryCheck = TRUE, noPatch = FALSE, showInfo = TRUE)   


**Error in antsImageHeaderInfo(files[1]) : File does not exist**


Thanks for your help and excuse me for these two questions (this is my first time using LESYMAP). 

Best,

**Comment by dorianps** [comment]
You are not passing the right lesion filenames. The code from the example
has find.package(), but that is only to get the filenames from the location
where the package is installed. Your filenames are probably somewhere else,
you need a vector of filenames and the behavior text file with the values
exactly in the same order.

Dorian

**Comment by marivas-MRI** [comment]
Dear Dorian

The registerLesionToTemplate function worked well with my images with the default template. However, I would like to perform lesymap's analysis using the aal atlas as template (find in attached). For that purpose I included this template in the registerLesionToTemplate function using the following loop: 


subjects <- c('E01_t1.nii', 'E02_t1.nii')     
lesions <- c('E01_lesion.nii', 'E02_lesion.nii')  

templateImg =antsImageRead ( '/home/miguel/Desktop/02_LINDA_IMAGES/aal.nii.gz')


for (i in seq_along(subjects)) {

    subImg = antsImageRead(subjects[i])    
    subLesion = antsImageRead(lesions[i])  

    subLesionCopy = antsImageClone(subLesion)    ### You recommended include this due to problems with header's images
    subLesionCopy = antsCopyImageInfo(subImg, subLesionCopy)

    temp = registerLesionToTemplate(subImg, subLesionCopy, templateImg, outprefix = paste0("reg_", sub("t1_(.*)[.]nii.*", "\\1", basename(subjects[i])), "_" ), saveDir = '/home/miguel/Desktop/02_LINDA_IMAGES/')

}


At the end of the registerLestionToTemplate there is a problem with registration. See the attached

![SCREENSHOT](https://user-images.githubusercontent.com/78478818/107766635-084e2c80-6d34-11eb-8ef8-fe2dd322b030.png)
 screenshot:

[aal.nii.gz](https://github.com/dorianps/LESYMAP/files/5971654/aal.nii.gz)

What could be wrong??

Thank you so much for your help. 


Best,

**Comment by dorianps** [comment]
@marivas-MRI 

I don't know what exactly is going on, but here are a few advice and things to check.
1. You are using MRIcron looks like. Try ITKsnap   when checking inputs and outputs from LESYMAP/ANTsR. ITKsnap uses the same image handling engine as these programs and will guarantee that what you see on the screen is what the software "sees" internally when processing images.
2. If you want AAL parcels, there are more efficient ways to get them. For example, you can register the MNI template onto the AAL template (using `antsRegistration()`), and use the registration fields  to bring to the MNI space the matrices (`antsApplyTransforms()`). You can also concatenate the deformation that you obtained when registering the subject to MNI with the deformation fields of the registration of the two templates, to bring the subject lesions in AAL space. In either case, you would not need to run individual subject registrations to AAL, you would run a single registration between templates and use the existing registration to MNI you might have.
3. The original registration run by LESYMAP on the included MNI template can be better because there are masks provided for the brain and the skull, which enable extracting the brain of the subject and registering brain on brain. If you can provide those masks for the AAL template, the results should be much better. This is, of course, if you still want to register each subject onto the AAL template.

**Comment by dorianps** [comment]
Btw, the MNI template used by lesymap is `ICBM 2009c Nonlinear Symmetric`. You can also google if someone has posted the AAL labels in that space.
