### ISSUE TITLE
LSM quesion: minimum number of subjects lesioned 

### ISSUE THREAD

**Issue by marivas-MRI** [dorianps/LESYMAP#30]
Dear Pustina, 

I am planning to use the LESYMAP tool to perform a LSM analysis. In LSM analysis context, is there a general rule about what should be the minimum number of subject lesioned at a voxel for that voxel to be included in the analysis (in LESYMAP the default option of minSubjectPerVoxel is 10%) ? I did not find a consensus about this point in the literature and would like if there is a recommended minimum threshold based on empirical evidence. 

Thank you very much in advance. 

Best regards,

**Comment by dorianps** [comment]
There is no rule of thumb because depends on several factors:
1. Lesion size - the larger the lesions the more likely they will overlap, and fewer voxels will be lesioned only on few subjects. On the other end, small lesions hardly overlap, so you can have 100 subjects with small lesions and have a hard time to run the analyses because minSubjectPerVoxel=10% may remove all voxels.
2. Sample size - the larger the sample, the higher the statistical power. You can imagine that 10% of 20 is 2. If your sample is  N=20, you may run t-tests on some voxels that compare a group of 18 subjects vs a group of 2 subjects. The power there may not be much, if any, but may be better if the sample size is 100. 
3. I would argue lesion patterns matter too, because one can have 100 lesion masks all in the same brain area, but that is another story. You should know that minSubjectPerVoxel=10% would remove also voxels >90% in LESYMAP, which is on the other end of the problem. But this hardly happens in practice because most lesion datasets struggle to have voxel that reach 50%, let alone going to 90%.

So, yes, there is no rule, but I would stick with what is in the literature. Some papers use 5%, I think that is way to low. Ultimately a good sample size can overcome some of the unbalanced voxel problems. You may want to check the papers by Chris Sperber, I think he looked into these issues before.
