### ISSUE TITLE
Effect size

### ISSUE THREAD

**Issue by WieTro** [dorianps/LESYMAP#31]
Dear Dorian

We were wondering if Lesymap provides also effect sizes for the SCCAN solutions? Or there a possibility to calculate them?
Thank you very much for your reply!

Kind regards
Wiebke

**Comment by dorianps** [comment]
No, SCCAN does not produce any effect sizes, and I am not sure how they could be calculated. The effect size is probably useful because p values do not provide info on the strength of relationship. Maybe the out of sample cross validated correlation can provide a similar understanding of that strength.

Pinging @stnava if he has any inputs on SCCAN effect size.

**Comment by WieTro** [comment]
Thank you for your reply!
