### ISSUE TITLE
Post-sccan cluster thresholding removed all voxels

### ISSUE THREAD

**Issue by ida030** [dorianps/LESYMAP#34]
Hello, 
I have been trying to perform SCCAN using dataset of 83 unilateral thalamic lesions, either with aphasia or without aphasia. I am trying to find out which thalamic site is specifically involved in aphasia.

I segmented the DWI-lesions manually (using MRICron) and standardized them into MNI space (using FSL).
After the SCCAN analysis is done I get the following warning: 

WARNING: Post-sccan cluster thresholding removed all voxels. 

Here is a complete output in the console: 

13:08:32 Running LESYMAP 0.0.0.9221
13:08:32 Checking a few things...
13:08:32 Filenames as input, checking lesion values on 1st image...
13:08:32 SCCAN method: ignoring patch, nperm, and multiple comparison...
13:08:32 Searching voxels lesioned in >= 10% subjects... 97 found
13:08:48 noPatch true - Patches will not be used...
13:08:48 Computing lesion matrix...  83x97
13:08:49 Checking matrix values are binary 0/1...
13:08:49 Running analysis: sccan ... 
       Searching for optimal sparseness: 
         lower/upper bound:	  -0.9 / 0.9 
         cvRepetitions:		  3 
         nFolds:		  4 
         sparsenessPenalty:	  0.03 
         optim tolerance:	  0.03 
13:08:49         Checking sparseness -0.212  . . .  CV correlation 0.295 (0.423) (cost=0.711) 
13:15:38         Checking sparseness 0.212  . . .  CV correlation 0.298 (0.423) (cost=0.709) 
13:22:31         Checking sparseness 0.475  . . .  CV correlation 0.325 (0.410) (cost=0.690) 
13:28:59         Checking sparseness 0.637  . . .  CV correlation 0.338 (0.415) (cost=0.681) 
13:41:56         Checking sparseness 0.738  . . .  CV correlation 0.344 (0.413) (cost=0.678) 
13:46:01         Checking sparseness 0.8  . . .  CV correlation 0.344 (0.417) (cost=0.680) 
13:51:54         Checking sparseness 0.728  . . .  CV correlation 0.343 (0.413) (cost=0.679) 
13:55:55         Checking sparseness 0.76  . . .  CV correlation 0.346 (0.416) (cost=0.677) 
14:00:57         Checking sparseness 0.775  . . .  CV correlation 0.343 (0.417) (cost=0.681) 
14:06:31         Checking sparseness 0.75  . . .  CV correlation 0.345 (0.416) (cost=0.678) 
14:11:10         Checking sparseness 0.76  . . .  CV correlation 0.346 (0.416) (cost=0.677) 
       Found optimal sparsenes 0.76 (CV corr=0.346 p=0.00136) 
       Calling SCCAN with: 
            Components:		 1 
            Use ranks:		 1 
            Sparseness:		 0.76 
            Cluster threshold:	 150 
            Smooth sigma:	 0.4 
            Iterations:		 20 
            maxBased:		 FALSE 
            directionalSCCAN:	 TRUE 
            optimizeSparseness:	 TRUE 
            validateSparseness:	 FALSE 
       WARNING: Post-sccan cluster thresholding removed all voxels. 
14:16:20 Preparing images...
14:16:20 Logging call details...
14:16:20 Done! 1.1 hours
 Lesymap Summary:
   Version             :0.0.0.9221
   Subjects            :83
   Method              :sccan
   Voxels in mask      :97
   Multiple comparison :none
   P-threshold         :0.05
   Statistic range     :0 0
   Significant voxels  :0
   Runtime             :1.1 hours
   ... save the output for more info ...

I was wondering what is the reason that my analysis fails. I have seen some published Lesion-Symptom-Mapping analyses using thalamic lesions with way less cases (n=20 or so), so I suppose it is not about the sample size ..? When I performed a simple subtraction analysis (aphasia-causing lesions minus lesions without aphasia) there was a significant overlap in each group, so I was surprised that this does not seem to be the case with SCCAN. 

Any suggestions on how to approach this problem would be much appreciated. 

Best regards, 

Ida

**Comment by dorianps** [comment]
What seems to be killing your results is the default cluster threshold of SCCAN. This is a parameter that was simply borrowed from ANTsR in the `sparseDecom2`, the SCCAN implementation lesymap uses. The parameter `cthresh` is used in the SCCAN iterations to remove tiny clusters that do not have much practical meaning (the original function helper is [here](https://rdrr.io/github/ANTsX/ANTsR/man/sparseDecom2.html)). That threshold makes sense in the cortical regions where 150 voxels are just 150mm3 = 0.15ml, which is very small to likely constitute a relevant finding.

In your case, your area of interest is very small, and you are interested in the tiny outcomes. So, you can decrease `cthresh` to the minimum cluster you think makes sense in the thalamus. And while you are at it, you may want to check the smoothing applied by SCCAN. The default sigma (argument `smooth`) is 0.4. This corresponds to about 2.355 * sigma = 0.942mm FWHM gaussian smoothing approximately.  It is not a lot but check it yourself if that amount of smoothing is appropriate given that your region is very small. Smoothing happens in the SCCAN iterations while seeking for a pattern of voxel weights. It is done to avoid single voxels popping out alone as relevant; we are interested in a region that collectively informs us (so smoothing does some regularization by melting individual values within the surrounding region). This is also the reason why SCCAN results look a bit smoothed.

Two more comments:
Rather than trying the subtraction method you mentioned, consider running the good old standard VLSM by switching the method from 'sccan' to a mass-univariate one. There will be no smoothing there, and no cluster threshold (check the arguments), so you can see if mass-univariate analysis gives you similar results. SCCAN and mass univariate will agree most of the time. But of course, avoid running the analysis 100 times until they look good to you. Fixing the above cthresh and smooth should give you what you need, and another single run of VLSM should give you more confidence on results. 

Second, SCCAN is honestly a misnomer myself and others keep using. Canonical correlations need multiple variables on each side, but in lesymap one side of the equation has only a single vector of behavioral scores. So, SCCAN is more simply used as a sparse regression. Keep this present when describing the method in the paper to avoid describing it as a standard canonical correlation, which the original algorithm is designed for but we are not using at full capacity in lesymap.

**Comment by ida030** [comment]
Thank you very much for your advice, this helped a lot!
