### ISSUE TITLE
SCCAN result interpretation

### ISSUE THREAD

**Issue by yangwei1993** [dorianps/LESYMAP#35]
Hi，I run SCCAN for my data, and I got a stat_img of two clusters. It was descripted in the info.txt document. I want to get the coordinate information of peak voxels in the two clusters. However, when I running the stat_img_bin in the fsl, I can only get one cluster, although I have try different threthhold. The script I used in the fsl is as follows:

"cluster -i /home/siying/sharefolder/VLSMdata/lsm/stat_img_bin.nii -t 0.02 -o cluster_index --osize=cluster_size > /home/siying/sharefolder/VLSMdata/lsm/cluster_info.txt"

I don't know  how to address the problem. Thank you so much.

**Comment by dorianps** [comment]
I don't use fsl and not sure how it works. Did you get stats_img_bin from lesymap or compute it separately? Wither way, there are other ways to find peak voxel locations. MRIcron used to have an option to go to closest peak if I remember correctly. ANTsR also can do that, but I don't remember exactly the functions right now. Certainly a binary mask is useless to find peaks (if stats_img_bin is just a binary map).

Word of caution: in multivariate methods like SCCAN (effectively used as sparse regression in lesymap) the interpretation of peaks is not straightforward. Voxel weights can change by simply changing the sparseness (see question "What happens when I increase sparseness" in the [Wiki](https://github.com/dorianps/LESYMAP/wiki/SCCAN-questions). Moreover, the SCCAN function smooths the weights during the iterations. Thus, a voxel does not represent anymore an "individual" relationship with behavior but carries weight in context with other voxels and exchanges a bit of weight value with neighbors due to smoothing. I would avoid too much interpretation of the peak voxel, which used to be reported and interpreted more for mass-univariate analyses.

**Comment by yangwei1993** [comment]
> 

Thanks for your kind explanation, and it helped me a lot. Wound you mind sharing me templete to describet the results of SCCAN, or one of your paper about SCCAN? Because I find there are positive and nagetive weights in my SCCAN resutl, and I don't know how to present or describe them in the results. I would appreciate you so much if you can help me. Then, I can learn how to write the results of SCCAN.Thank you again.

**Comment by yangwei1993** [comment]
> The original paper is here: https://pubmed.ncbi.nlm.nih.gov/28882479/
> 
> The directionality of voxel weights (negative vs positive) was added to LESYMAP after the original publication. The wiki describes the rationale [here](https://github.com/dorianps/LESYMAP/wiki/What's-new-in-v0.0.0.9201). I have not been doing LSM analyses for a while, but there are many papers that have used SCCAN (see "Cited by" section in Pubmed).
> 
> I would suggest you run a traditional VLSM (mass-univariate) analysis alongside sccan to make sure the results have similar direction and spatial distribution (SCCAN should not produce completely different results). You can use method ttest or BM, depending on the data. Even if you don't put them in the main manuscript, you can put them in supplementary material to show the reviewers you did try the mass-univariate approach for consistency.
> 
> The directionality of weights in sccan should depend on the relationship between voxel lesion and behavior. Lesion = 1, noLesion=0. If behavioral score goes down for lesions, it should have a negative relationship (think a negative correlation). But double check anyway because as I said I have not tested the voxel directionality thoroughly.

Thanks for your reply.
