### ISSUE TITLE
BLAS/LAPACK routine 'DLASCL' gave error code -4

### ISSUE THREAD

**Issue by yizhwan** [dorianps/LESYMAP#36]
Hi, 

I have tried running lesymap method 'regresfast' on a 100 subjects with 1 behavioural vector. I have tried using the following combinations:

# run a ULSM on GM roi
for (r in lesioned_gm_names) {
  lesymap(eval(parse(text = qq(paste0("lesion_f_@{sample}")))), behavload_gm[, r], mask = NA, patchinfo = NA, 
          method = "regresfast", correctByLesSize = "both",
          multipleComparison = "FWERperm", pThreshold = 0.05, flipSign = F,
          minSubjectPerVoxel = 5, nperm = 1000, saveDir = paste0(qq("/lesymap_results/left/samples/@{sample}/smooth/@{smooth}/noise/@{errorw}/regress/"), r),
          binaryCheck = FALSE, noPatch = FALSE, showInfo = TRUE)
}

1. Ubuntu 22.04 LTS with Docker- no error messages thrown but no results showing after > 24 h.
2. Mac Intel i9 with Docker-  no error messages thrown but no results showing after > 24 h.
3. I then downloaded Lesymap on Ubuntu 22.04 LTS locally via R and ran the same command resulting in:

warning: solve(): system is singular; attempting approx solution
Error in regresfast(lesmat, behavior, covariates, hascovariate) : 
  BLAS/LAPACK routine 'DLASCL' gave error code -4

I am surprised since SCCAN runs fine, only regrefast results in this error?

**Comment by yizhwan** [comment]
I should add that I have ran regresfast only 2 weeks ago via Docker with no problems with exactly the same code.
Any light you could shed would be very helpful.

Thanks.

Yizhou

**Comment by dorianps** [comment]
I am not sure what is happening. Searching for that BLAS error code in Google does not produce much to go on. The problem is only in the regression routine, something that BLAS needs to solve. SCCAN may use some other library for math calculations (not 100% sure).

You are also saying that the same exact code and data worked few weeks ago. So what changed? Which docker image are you using? I see I have not pushed docker images for at least 4 months, but I have not touched lesymap or docker recipies for longer than that, so nothing has changed on my end. I also rely on a specific docker base image from 3 years ago, so I don't think something has changes in the docker image during my builds. But I have to admit that I don't use or test the docker images much.

One guess would be that during the permutations of the data, something happens that the solution becomes impossible to solve. Do you really need to apply correction for lesion size on both the voxels and the behavior? What would be the point of that, I am not sure? If you don't need both, remove the correction on voxels and leave correction only on the behavior (the good old way). I put those option "both" for lesion size correction because I think someone asked for it, but I don't understand why should lesion size be removed on both on behavior and voxels. Conceptually, lesion size affects behavior and the voxel correction proposed by Zhang 2014 was done only to avoid the heavier correction done directly on behavior, not to add to it.

On a side note, since you are during heavy computations, see if using a faster BLAS implementation can help speed regressfast in the local R install. Instructions are here: https://github.com/ANTsX/ANTsR/wiki/Installing-ANTsR-on-Windows-10-(using-WSL2)#faster-r-processing-optional
If you notice a speedup, maybe I can try to include those libraries in the docker images.

**Comment by dorianps** [comment]
Please post the full log if you still see errors.

**Comment by dorianps** [comment]
Did you manage to resolve the issue?

**Comment by yizhwan** [comment]
Hi, 

Thanks for the suggestions. I changed the volume correction to behaviour only and the code now works!
