### ISSUE TITLE
Error with multiple comparisons correction

### ISSUE THREAD

**Issue by avrvaidya** [dorianps/LESYMAP#4]
I am trying to replicate some of my previous results that I have found with NPM using the lesymap toolbox, but I am getting strange outputs depending on what I set for the multiple comparisons option.

When I ask for BM tests or t-tests using FDR, Bonferroni or holm (I haven't tried all the options), lesymmap produces z-maps with uniform zeros. Like below:

> Lesymap Summary:
>   Subjects            : 27 
>   Method              : ttest 
>   Voxels in mask      : 107372 
>   Method              : ttest 
>   Multiple comparison : fdr 
>   P-threshold         : 0.05 
>   Statistic range     : 0 0 
>   Significant voxels  : 0 
>   Runtime             : 8.1 secs 

>   Version             : 0.0.0.9003 

If I change the multiple comparisons option to a meaningless string ("hjhjh"), I get non-zero values. Here is an example with t-tests :

>  Lesymap Summary:
>   Subjects            : 27 
>   Method              : ttest 
>   Voxels in mask      : 107372 
>   Method              : ttest 
>   Multiple comparison : hjhjh 
>   P-threshold         : 0.05 
>   Statistic range     : -3.6 3.2 
>   Significant voxels  : 107372 
>   Runtime             : 8.1 secs 
>   Version             : 0.0.0.9003 

With this meaningless string, the t-test values look reasonable to me, but the BM Z-scores are on an unreasonably wide range:

> Lesymap Summary:
>   Subjects            : 27 
>   Method              : BM 
>   Voxels in mask      : 107372 
>   Method              : BM 
>   Multiple comparison : hjhjh 
>   P-threshold         : 0.05 
>   Statistic range     : -50.9 14 
>   Significant voxels  : 105444 
>   Runtime             : 14 secs 
>   Version             : 0.0.0.9003

Not sure what I might be doing wrong here?

Thanks again,
Avi

**Comment by dorianps** [comment]
T scores look pretty low. I'm not surprised the correction kills them all.
They also look ranging equally both negative and positive which is a bit
unusual.

Two questions:
1. Are behavioral scores decreasing or increasing for lesioned voxels?
Lesymap expects lesions to produce lower scores.
2. Have you checked stats.img itself instead of zmap.img for BM? Does it
give a reasonable output?

**Comment by avrvaidya** [comment]
The behavioral scores are coded so that negative scores = worse performance
in this task.

Stats.img seems to reflect the range of stats in the lesymap summary, which
I assume is meant to be thresholded at pThreshold. However, even when I
have significant results according to some threshold, the z-score map is
blank.

I also think that the thresholding for the stats and z-score images is not
working properly... When I run the same analysis with a pThreshold set to
0.9, I get the exact same results as a threshold of 0.05.

Again, I am also surprised that the stats for the BM test are so different
from NPM. For reference, when I reran this analysis in NPM, the t-stats
range from -2.9-3.2 (where as the range is -3.2-3.6 in lesymap), and the BM
z-scores ranged from -2.96-3.20 (while lesymap gives a range of -50-14).

Thanks again for your fast responses!
Avi

**Comment by dorianps** [comment]
Hi Avi,

There was a small bug that skipped thresholding maps when `multipleComparison='none'`. I should have fixed it in the last commit a few minutes ago. Update the package to have it take effect.

What you described above might very well come come because you selected an unknown multiple comparison method. That was considered same as no threshold at all. The last commit has a new check, so now you will receive an error if multipleComparison is unkown.

Please check if this fixes the p-value issue. Then check if the maps you get  from stat.img or zmap.img are similar to what you get from MRIcron. If the spatial match is good but values are wrong, I will need to run some troubleshooting with examples with small sample sizes like yours.

Dorian

**Comment by avrvaidya** [comment]
Great! That seems to have fixed the thresholding problem for t-tests.

It looks to me like the t-tests are providing mostly sensible answers...
The stats map, z-values and spatial pattern match what I find using NPM,
though the values continue to be higher in both directions, as I mentioned
before.

However, with BM tests, I am continuing to get very weird results. The
spatial match is more or less accurate, but is weirdly spotty... Here are
comparisons of results in NPM and with lesymap (both unthresholded):

NPM:
[image: Inline image 1]


Lesymap (patches off):
[image: Inline image 2]

The values are also far off: the lesymap range is still between -50-14.

The spottiness only appears with I have the patch option turned off. With
patches turned on, the spatial pattern looks better, but is still over a
much larger range than in NPM (lesymap: -7.2-14):

Lesymap (patches on):
[image: Inline image 3]

I have also noticed that even when using Bonferroni, or no multiple
comparison correction, Lesymap seems to be running permutations for BM
tests, but not for t-tests.

Thanks again,
Avi

**Comment by dorianps** [comment]
Images didn't get through. You can post them on the github issue page and they will show:
https://github.com/dorianps/LESYMAP/issues/4

> The spottiness only appears with I have the patch option turned off. With
patches turned on, the spatial pattern looks better

I don't think you should switch patches off. MRIcron also runs patch-based analyses. With small sample sizes there are a lot of voxels with identical patches that just increase the number of multiple comparisons if analyzed all.

> I have also noticed that even when using Bonferroni, or no multiple
comparison correction, Lesymap seems to be running permutations for BM
tests, but not for t-tests.

This is intentional. BM tests needs permutations at the voxel level if one of the groups has less than 9 subjects (see [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2795086/). Your sample will have a lot of voxels below that value, so you see permutations being run for those voxels. T-tests are not subject to the problem, so you just see standard voxel-wise tests. Note that permutations for BM are done at each voxel, which is different from permutation-based multiple comparison corrections (`multipleComparison='FWERperm'`). By the way, if you are comparing lesymap with mricron, try the permutation based multiple comparison on both, that is one of the most robust thresholding mechanisms.

> the values are also far off: the lesymap range is still between -50-14.
This is what I am trying to understand. The BM method in lesymap currently relies on the nparcomp package. Will need to check if that package is giving back reasonable values.

**Comment by avrvaidya** [comment]
Here are the un-thresholded BM stats from my last post:
NPM:
<img width="347" alt="screen shot 2017-10-20 at 3 24 59 pm" src="https://user-images.githubusercontent.com/32939243/31840659-561c1c3c-b5b4-11e7-8be0-a01425f7dd76.png">

Lesymap (no patches):
<img width="341" alt="screen shot 2017-10-20 at 3 24 19 pm" src="https://user-images.githubusercontent.com/32939243/31840665-600e00a2-b5b4-11e7-8087-ce232c843536.png">

Lesymap (patches):
<img width="340" alt="screen shot 2017-10-20 at 3 32 05 pm" src="https://user-images.githubusercontent.com/32939243/31840695-7b672572-b5b4-11e7-8ea9-f473553ad801.png">

Using FWERperm for multiple corrections and BMfast tests, my results also diverge from NPM. In NPM, the FWE permutation threshold was Z = -3.21 for p = 0.05 (with lower scores = worse performance). In that analysis, I had voxels crossing that threshold at Z = -3.32. In lesymap, nothing comes out significant with FWERperm and patches. If I drop the threshold by a lot (p = 0.5), then I get a few voxels with very high Z values (Z = 14), and a few other small patches (Z=2.67), but these are all in the opposite direction of my NPM results, and in different locations.

**Comment by dorianps** [comment]
Looks like NPM (which uses patches) matches Lesymap's output with patches. The scattered results might come from the stronger correction for multiple comparison, but it also looks like you are using MRIcron to view the data, which has it's own automatic thresholding when overlays are displayed. Either check the automated threshlding in MRIcron, or use ITKsnap. Note that ITK-based software (Snap, ANTsR, Lesymap) use a different part of the header to orient the image from other ones (MRIcron, SPM, FSL). Sometimes this creates problems, so the best way is to visualize the results on a software that reads the data in the same way they were read during analysis. 

About FWERperm, there is actually a difference between NPM and LESYMAP, but I that that difference was small. NPM actually computes and stores zscores, while LESYMAP stores the statistical BM t-score. The threshold computed in NPM is actually on the zscore distribution of permuted data, while for LESYMAP is currently on the BM t-score distribution.  This should not create major differences but you never know (zscores depend on the degrees of freedom, which differ at each voxel).

Without knowing the data cannot tell much, but if the range of t-test scores is really -3 to 3, the signal doesn't seem to be strong.

Happy to have a look if you want to share the data. Meanwhile you can try also `method='sccan'` to see if multivariate is giving you anything.

**Comment by avrvaidya** [comment]
Sorry about the long delay, but I was out of town for a few days. I tried a few things with SCCAN and compared the output with the BM tests in LESYMAP and NPM.

The stats output of SCCAN at the p < 0.05 threshold ends up giving similar results to NPM+permutation FWER: 

NPM BM, FWER (red), LESYMAP SCCAN (blue)
<img width="288" alt="screen shot 2017-10-25 at 3 32 21 pm" src="https://user-images.githubusercontent.com/32939243/32019002-bf74cb32-b999-11e7-81b7-f6566e72ebf8.png">

However, I do not see an p-values in the LESYMAP 'pval' file.
 
If I drop the SCCAN threshold to p = 1, I get a similar stat map with a somewhat larger area and some additional nearby clusters. The p-value map is still blank though.

To me, it looks like SCCAN and NPM+BM with permutation FWER agree better than LESYMAP's BM+FWER tests (where nothing passes the p < 0.05 threshold). I am wondering if this might be due to some of the extreme raw BM values driving the permutation threshold up in SCCAN. As you alluded to, this might be more of a problem in cases like mine with relatively few subjects per voxel.

**Comment by dorianps** [comment]
Interesting, looks like you have a robust enough result. What SCCAN cross-validation you get? You can also use `save.lesymap` to save the result somewhere, and copy-paste the text file that is produced.

The `pval` image is always be empty with SCCAN, because there is no "voxel-wise" statistics to compute. There is no null hypothesis at the voxel level. The same is true for FWERperm, which is a global threshold of permutation. I don't know what NPM is producing, but there should not be any voxel level p-values for volume permutation thresholds. Maybe they put in there the values of voxel-wise stats. But I think that might mislead researchers, so the pval map is empty when the chosen analysis cannot produce a pval map.

The p-value that you set for SCCAN is very different from what you might be used to. It is applied to the cross-validated correlation to check whether the correlation is significant to the point that the result can be retained. When you change the threshold you don't get any "more" or "less" significant voxels, because SCCAN converges on its own to the appropriate sparseness (sparseness controls the extent of results). You can manually set a higher sparseness if you want to see more extensive results.

Before we proceed with other checks to see if Lesymap's FWER has a problem, did you remove MRICron's thresholds and clippings? Are you sure there are no values in the outcome maps where there should be?

Thank you for trying things out.
Dorian

**Comment by avrvaidya** [comment]
The optimized sparseness for that analysis (with the p-threshold set to 0.05) was 0.051. The CV correlation was 0.425, p = 0.03.

In NPM, the FWER permutation analysis will give you thresholds for BM z-scores at the p<0.05, 0.01 etc, levels. My understanding to date was that these permutation tests were carried out at the voxel level, but I will have to check this. Do you have a citation?

> Before we proceed with other checks to see if Lesymap's FWER has a problem, did you remove MRICron's thresholds and clippings? Are you sure there are no values in the outcome maps where there should be?

I am not sure what you are referring to by 'thresholds and clippings.'  The outcome map overlaps with areas where I have sufficient power in my lesion masks. I've checked all the masks previously, and they are all binary nifti files in the standard space.

Thanks a lot for your explanations!
Avi

**Comment by dorianps** [comment]
I am not 100% sure all the details of how NPM works but I think it has
permutations at the volume level. You can read the Lesymap wiki which also
has the references to understand permutations.

https://github.com/dorianps/LESYMAP/wiki/Understanding-permutations


About visualizing in MRIcron, I remember some years ago that MRIcron does
some kind of self-thresholding, i.e., removing the values above the 99th
percentile. It used to be a problem for me because I thought all the
results were displayed and then I found that I had to manually set the
thresholds. This may be just my experience, or a wrong memory, but you
should have a look at the range of the data that MRIcron shows, whether
goes between min and max values. If, by any chance, the full range is not
displayed automatically, you may not see some of the voxels that actually
have values.


Out of curiosity, is the result you showed above related to a real
cognitive deficit? It is interesting to see such a focal result in that
area of the brain.

**Comment by avrvaidya** [comment]
Thanks for the link! I misunderstood your description of NPM in your earlier post. I thought that you were suggesting that NPM was carrying out permutations at the level of voxel clusters, rather than permuting behavioral scores (at least for voxels with N > 9).

> This may be just my experience, or a wrong memory, but you
> should have a look at the range of the data that MRIcron shows, whether
> goes between min and max values. If, by any chance, the full range is not
> displayed automatically, you may not see some of the voxels that actually
> have values.

I have also had experience with this in MRIcron. However, I checked the full range of the BM FWER thresholded results, and they definitely do not match the results from NPM or SCCAN.

> Out of curiosity, is the result you showed above related to a real
> cognitive deficit? It is interesting to see such a focal result in that
> area of the brain.

This result was from a study we did on attentional priming by rewarding stimuli in frontal lobe damaged subjects (https://www.ncbi.nlm.nih.gov/pubmed/26377468). We found that damage to that area (ventromedial frontal lobe) was associated with reduced reward priming. Our patient population included subjects with different kinds of damage (e.g. tumor resection, stroke, aneurysm), which may have reduced some of the covariance between lesioned voxels, and the association between damage and the vasculature.

**Comment by dorianps** [comment]
Nice.

Another thing to try if you want to see if NPM and Lesymap resutls are consistent is repeat the data from your 27 subjects to go above 90. In R you can do something like `behavior = c(behavior, behavior, behavior, behavior)`. Once you do that, you can use `method='BMfast'`. Actually that is enabled for permutation based multiple comparison, so you can select `multipleComparison='FWERperm'` or the good old `multipleComparison='fdr'`. Then you can compare with the results you get from NPM (just copy paste the lines in the .val file.

The above can help understand if there is anything different between NPM and LESYMAP when no voxel-wise permutation is needed.

**Comment by avrvaidya** [comment]
I tried artificially quadrupling my subjects like you suggested (N = 108) in LESYMAP. When I ran BMfast tests with FWERperm corrections, I got a similar statistical map to LESYMAP's analysis using 27 subjects. The range of BM statistics is unsurprisingly higher (0-565.7), but the location LESYMAP identifies is still very different from BM tests in NPM and SCCAN:

Here is the BMfast FWER-permutation corrected map with 108 "subjects":
<img width="528" alt="screen shot 2017-10-27 at 11 44 25 am" src="https://user-images.githubusercontent.com/32939243/32112783-354e90a4-bb0c-11e7-9c5f-9f9942a46086.png">


This area appears to correspond to the positive effects in my study (i.e. where damage was associated with higher reward priming). It shows up in the SCCAN analysis with a pthreshold set to 1, and is also non-significant in the NPM BM analysis.

**Comment by dorianps** [comment]
Avi, not sure I understand. Which area is significant (or non significant) in NPM, and which one is mismatched in Lesymap? 

You should ignore the value range as a comparison to NPM, because NPM only outputs zscores I think.

**Comment by dorianps** [comment]
Also, if there is something really wrong with BM or BMfast, that should not happen with t-tests, so you can try that too. I remember getting fully matching maps between NPM and Lesymap zscores with 130 subjects. If you keep finding major differences, I can try to test your dataset.

Also, check the NPM version you have is the latest one.

**Comment by avrvaidya** [comment]
For comparison, here are my results from BM tests using NPM (red, uncorrected), showing which voxels are associated with a lower score, and the SCCAN results at pthreshold = 1 (blue):

<img width="378" alt="screen shot 2017-10-27 at 1 57 19 pm" src="https://user-images.githubusercontent.com/32939243/32118377-78ee454e-bb1f-11e7-9afa-b2adad54c90f.png">

You can see that there is a good correspondence between both results indicated by the purple color where they overlap.

If you look at the voxels associated with higher scores in NPM, there is a small non-significant cluster of voxels in a dorsal area, below the permutation threshold:
<img width="408" alt="screen shot 2017-10-27 at 1 59 44 pm" src="https://user-images.githubusercontent.com/32939243/32118514-f3dc9ed6-bb1f-11e7-8d9d-68ce0875654a.png">

BM tests with correction for multiple comparisons in LESYMAP do not yield any significant results. However, at an uncorrected threshold, the only significant results are this small set of dorsal voxels:
<img width="384" alt="screen shot 2017-10-27 at 2 07 19 pm" src="https://user-images.githubusercontent.com/32939243/32118653-79a90c02-bb20-11e7-8d8b-eff5d5af06b7.png">


The same result comes up for BM tests with the artificially inflated N, like I showed in my last post (the extent is wider because more voxels are being included in the analysis):
<img width="383" alt="screen shot 2017-10-27 at 2 07 35 pm" src="https://user-images.githubusercontent.com/32939243/32118662-7ea88304-bb20-11e7-86ae-d77c247cfccc.png">


The t-statistic map looks similar to my BM results in NPM and the SCCAN results. Here is the uncorrected t-map for lower scores:

<img width="381" alt="screen shot 2017-10-27 at 2 21 23 pm" src="https://user-images.githubusercontent.com/32939243/32119128-446602fa-bb22-11e7-98eb-5b75cefed63f.png">

And the uncorrected t-map for higher scores:
<img width="397" alt="screen shot 2017-10-27 at 2 22 03 pm" src="https://user-images.githubusercontent.com/32939243/32119141-4cffe020-bb22-11e7-8bc3-b739e5d80339.png">

**Comment by dorianps** [comment]
Ok, that shouldn't happen. Can you share the dataset so I can have a look? You can use wetransfer and send me an email at albnet at gmail dot com.

In principle, however, it's not a good idea to see uncorrected results. The overlap of uncorrected BM with SCCAN may not overlap at all once the results are properly corrected.

**Comment by dorianps** [comment]
Hi Avi, thanks for sending the data.

Had a quick look and I partly understand is going on.

First, I had some troubles to get zmap.img from lesymap. This might be a bug in itself, but I don't think is causing any problem. You can still see the outcome in stats.img.

Looks like the orbitofrontal finding has a positive relationship with the lesion. Lesioned voxels have higher value. If I  invert the behavioral scores and I run lesymap with these paramters, I get a single cluster:
```
Time: 2017-10-28 19:42:40
LesymapVersion: 0.0.0.9005
method: BMfast
correctByLesSize: none
multipleComparison: FWERperm
pThreshold: 0.05
flipSign: FALSE
minSubjectPerVoxel: 10%
nperm: 5000
saveDir: NA
binaryCheck: FALSE
noPatch: FALSE
showInfo: TRUE
Subjects: 27
patchinfo: Computed
Runtime: 6.4 secs
Total voxels in mask: 107372
Unique voxel patches: 387
Average patch size: 277.4 voxels
Unique single voxels: 43
Range statistic: 0 50.91
Suprathreshold voxels: 186
Number of Clusters: 1
Cluster sizes (voxels): 182
Cluster sizes (mm3): 182
perm.FWEthresh: 24.7487373415293
```
![image](https://user-images.githubusercontent.com/9083517/32139679-8c0e1a1e-bc1e-11e7-991d-8f8f3a4877f3.png)

This looks similar to what you showed before. I think this finding is also quite close to the significance threshold, and is coming up because lesymap is calculating a one-sided test.

When I run the same in NPM, I get a continuous unthresholded map. It has the negative scores in orbitofrontal and positive scores in superior frontal.

```
Total voxels = 7109137
Only testing voxels damaged in at least 3 individual[s]
Number of Lesion maps = 27
Permutations = 4000
Analysis began 28-October-2017 19:55:05
Voxels damaged in at least 3 individuals = 107372
Memory planks = 0.00539989024400711
Generating BM permutation thresholds
107372 test Std Bonferroni FWE Z 0.050=4.906, 0.025=5.040, 0.01=5.213
387 test (Number of Unique Lesion Patterns with at least 3 lesions) Bonferroni FWE Z 0.050=3.654, 0.025=3.828, 0.01=4.048
BM Range -3.390...3.011
BM +FDR Z 0.050=9.20000000, 0.01=9.20000000 
BM -FDR Z 0.050=9.20000000, 0.01=9.20000000 
BM+: permutationFWE , 0.050=3.40984416, 0.025=3.71901655, 0.01=3.89059186 
BM-: permutationFWE , 0.050=-3.38957906, 0.025=-3.50887871, 0.01=-3.71901655 
Analysis finished 28-October-2017 19:56:03
Processing Time (seconds) 58
```
![image](https://user-images.githubusercontent.com/9083517/32139701-32475828-bc1f-11e7-9214-1d313b9693ab.png)

If I threshold this map to keep significant negative or significant positive scores, there is nothing significant:
```
> tem = antsImageRead('npm_perm/rewpriming_resultsBMPred1.nii.gz')
> range(tem)
[1] -3.389579  3.011454
> sum(tem>3.409 & tem < -3.389)
[1] 0
```
In essence, there is no significant result in NPM from what I can see. At least not with a dual sided hypothesis (I don't know how to test one sided hypotheses in NPM). The above threshold is also very relaxed 0.05 negative and 0.05 positive, which is effectively 0.1.

The significant result you get in LESYMAP is probably because by default `alternative = 'greater'`, meaning that 0-voxels are expected to have higher behavioral scores than 1-voxels. I gave it a try to switch to `alternative='two.sided'` but I may have done something wrong in the code and I got the values in between instead of getting the most extreme tails of the distribution. The way I coded two-sided thresholds might also need a review, because I currently use an "absolute" strategy, meaning that I simply turn the negative values to absolutes before computing the quantile of the permutations. Will need the opinion of a statistician if my choice is wrong.

So, strictly speaking the LESYMAP outcome is not wrong, because is expecting a specific relationship direction. It still needs some work with zmap calculation and two-sided hypotheses, but there is some good agreement between the two software. To reiterate what I mentioned above, NPM does not give any result with permutation FWER.

Now, let's think about SCCAN. You got a decent result, which had some good cross-validation accuracy. Obviously you have noted that your chance of getting any result somewhere is slim with any method, because most of the voxels have small lesion rate. This said, your SCCAN outcome was also borderline significant at p=0.03. It can hold if your hypothesis is one sided, but if your hypothesis is two-sided, you can try to run two different SCCAN analyses, one with the original order of behavioral scores, and the other with the inverted order (`behavior = -behavior`). In that case you should try each of them with p=0.025, and this will obviously kill your original finding. In short, this result would not be that different with the NPM result, and with what seem to be a set of results close to the borderline significance.

Hope all of this makes sense. I realize some of the lesymap behavior may be buggy, and I'am happy to put my hands into the code to fix those. But first let's try to understand your data, then we can see how to resolve lesymap's misbehavior.

Let me know if you have other questions.

**Comment by dorianps** [comment]
To clarify something from above. The cluster I find in Lesymap has also the most negative values in NPM, so  that cluster according to both software is more "significant" than the anterior one, according to BM analyses. T-test may produce a different outcome because they run a different type of analysis...

**Comment by dorianps** [comment]
And one more follow-up.
SCCAN at the sparseness you mentioned gets both clusters, the posterior orbitofrontal and anterior orbitofrontal. It gives more weight to the anterior one, maybe because it is surrounded by other good voxels, while the posterior one has less weight, maybe because it's on a single slice and does not hold well when smoothing is applied in SCCAN iterations. Cross-validation and p-value is worse that what you mentioned above.

```
Time: 2017-10-28 21:03:21
LesymapVersion: 0.0.0.9005
method: sccan
correctByLesSize: none
multipleComparison: none
pThreshold: 0.05
flipSign: FALSE
minSubjectPerVoxel: 10%
nperm: 5000
saveDir: NA
binaryCheck: FALSE
noPatch: TRUE
showInfo: TRUE
sparseness: 0.051
alternative: two.sided
Subjects: 27
patchinfo: not computed
Runtime: 33 mins
Range statistic: 0 1
Suprathreshold voxels: 661
Number of Clusters: 2
Cluster sizes (voxels): 483 178
Cluster sizes (mm3): 483 178
optimalSparseness: 0.051
CVcorrelation.stat: 0.385720424753283
CVcorrelation.pval: 0.0469136637685666
```

![image](https://user-images.githubusercontent.com/9083517/32140095-c425c8d2-bc2a-11e7-9ef5-402e960521b0.png)

![image](https://user-images.githubusercontent.com/9083517/32140096-d6e74aa4-bc2a-11e7-8e78-877af995004c.png)

**Comment by dorianps** [comment]
The latest commit https://github.com/dorianps/LESYMAP/commit/c84b361a7ecf0f3e155730381b29adfc0831c119 has the fix to run BMfast with two-sided expectation. Please update the package to have it take effect.

You can run something like: 
```lesymap(..., multipleComparison="FWERperm", alternative="two.sided"``` or `alternative="less"` or `alternative="greater")`.

With your data, you can get significant voxels at pThreshold=0.1 two-sided, or at pThreshold=0.05 one-sided.

**Comment by avrvaidya** [comment]
Hi Dorian, thanks a lot for taking the time to look into this in detail. 

Unfortunately, the new update crashes for me. When I try to load the latest version of LESYMAP, I get the following error:

> Error in get0(".packageName", env, inherits = FALSE) : 
>   lazy-load database '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/ANTsR/R/ANTsR.rdb' is corrupt
> In addition: Warning message:
> In get0(".packageName", env, inherits = FALSE) :
>   internal error -3 in R_decompress1
> Error: package or namespace load failed for ‘LESYMAP’

If I understand your response correctly, the issue was that LESYMAP BM tests were testing which voxels were associated with higher behavioral scores? This is why you had to invert the scores or change the alternative hypothesis before running the tests?

I also tried to re-run our NPM analysis in the latest version and got the same results as you. The results I mentioned earlier came from our original analysis using the June 6, 2013 version of NPM. I am not sure why the BM test results are so different (the problem mentioned by Medina et al. was supposed to be fixed in that version). The posterior OFC result does appear to be right at the p = 0.05 permutation threshold though (Z = -3.3895), which is a little reassuring. The more anterior result definitely does not survive though.

**Comment by dorianps** [comment]
One small errata above.

I said NPM does not give any result when using 400 permutations, but that was my mistake. It actually gives 186 voxels:
```
> tem = antsImageRead('npm_perm/rewpriming_resultsBMPred1.nii.gz')
> sum(tem>3.409 | tem < -3.389)
[1] 186
```
And they are the same identical voxels that LESYMAP gives with BMfast, FWERperm, 4000-5000 permutations. The match of the finding is one-to-one. BMfast does not give zscore maps on purpose. 
![image](https://user-images.githubusercontent.com/9083517/32146933-0b01ed8c-bcb5-11e7-8f08-c47747220552.png)


Are you saying you found different results between NPM 2013 and NPM 2016?

I am running a couple more tests to figure out what zscores is NPM computing.

**Comment by dorianps** [comment]
Added some code in https://github.com/dorianps/LESYMAP/commit/08144f679e788d2b5c04a732839ee52ba79b99f7 to fix zmap issues. You can get zscores now, and they follow the same pattern as NPM, but the exact values are different. It's kind of difficult to understand NPM's approach. BM scores are supposed to be t-scores, but I remember a while back that NPM uses the normal distribution to compute zscores, instead of the t-distribution, which I thought would be appropriate. Moreover, BM tests have a problem of reaching infinite values when the two groups of voxels separate behavioral scores perfectly without overlap. A solution implemented in some software is the addition of a small value to avoid getting infinite computations.

Let me know if there is anything else that is off place. Thanks for trying lesymap.

**Comment by dorianps** [comment]
About your installation error, looks like the ANTsR installation is corrupt. Try `remove.packages('ANTsR')` and install again. There is some more suggestions in stackexchange:

https://stackoverflow.com/questions/30424608/error-in-fetchkey-lazy-load-database

**Comment by avrvaidya** [comment]
Nice to see that the posterior OFC result survives!

> Are you saying you found different results between NPM 2013 and NPM 2016?

Yes. In NPM 2013, the anterior medial OFC and posterior OFC effects were both lower (Z values of 3.23 and 3.32, respectively). The permutation threshold for this version of NPM was also a good deal lower (Z>3.21 for p < 0.05 (keep in mind that this version of NPM automatically multiplies all behavioral scores by -1, so that lower scores = higher Z scores)).  

Thanks for the tip. The new installation seems to be working fine. I can also see the z-score map. As you say, the results correlate well with NPM, but do not perfectly match their values.

Thanks again for all the help!

**Comment by dorianps** [comment]
Avi,

I have pushed a new lesymap version which addresses two issues that came up here:
1. There is a new compiled permutation based Brunner-Munzel engine, which runs all statistics without the need for the external `nparcomp` package. You can simply use `method='BMfast'` and the voxels that require permutations will use the new code.
2. I noticed the old `method='BM'` uses a small number of permutations by default, i.e., 1000 instead of 20000. The user was supposed to set manually a higher number of permutations when using BM, but you may not have known it. I have added some checks and warning messages to inform the user when the number of permutations is too low. The new BMfast engine uses 20000 perms by default, so you will be able to find lower p-values when there is good signal. Note that these permutations do not affect at all the results obtained with `multipleComparison='FWERperm'`, they only affect single voxel p-values when the number of subjects is kind of small.

**Comment by avrvaidya** [comment]
Hi, sorry for the delayed response... 

I tried running the BMfast tests with FWERperm after updating LESYMAP, but I am getting the following error:

> 15:05:50 Running LESYMAP 0.0.0.9007 
> 15:05:50 Checking a few things...
> 15:05:50 Computing mask from average >= 3 ...
> Error in lesymap(files, scores, patchinfo = NA, method = "BMfast", correctByLesSize = "none",  : 
>   Mask is empty. No voxels to run VLSM on..

This is a new one for me. It  doesn't seem specific to BMfast (I get the same errors for BM tests or SCCAN).

Avi

**Comment by dorianps** [comment]
Closing the issue, please open new one if needed.
