### ISSUE TITLE
Error in makeImage(mask, voxval = statistic[voxindx]) :    unused argument (voxval = statistic[voxindx])

### ISSUE THREAD

**Issue by yizhwan** [dorianps/LESYMAP#40]
Dear team, 

I seem to be getting an error with preparing the statistic images, please see below: What could be causing this? Thanks.

23:25:29 Running LESYMAP 0.0.0.9221
23:25:29 Checking a few things...
23:25:30 Searching voxels lesioned in >= 5 subjects... 7173 found
23:25:30 Computing unique patches...
23:25:33 Found 108 patches in 7173 voxels - 66.4 times more voxels
23:25:33 Using existing lesion matrix...  50x108
23:25:33 Correcting for lesion size: behavior...
23:25:35 Correcting for lesion size: voxel...
23:25:38 Running analysis: regresfast ... 
        FWERperm 1000 permutations   - expected run = 0.2 secs 
 WARNING: Infinite values detected in zscore.
23:25:38 Preparing images...
Error in makeImage(mask, voxval = statistic[voxindx]) : 
  unused argument (voxval = statistic[voxindx])

**Comment by dorianps** [comment]
I can think of two possibilities off the top my head.

1. The regression formula is not solving the problem for some of the
voxels, likely due to some perfect fit or something like that. The problem
then propagates to statistic[voxindx], but why it complains that voxval is
unused argument. I am a bit rusty with using R nowadays, so the error is
not promptly ringing a bell.

2. You have another package that is overriding the makeImage function. I
checked the ANTsR function and it still has the voxval argument available,
so there is no reason to complain about it, unless it's not the original
function.

**Comment by dorianps** [comment]
Try also running method 'regress' instead of 'regressfast'. Regressfast was
my implementation in C++, and maybe I forgot to fix some weird case
(although I thought I addressed the NaN issues).

**Comment by dorianps** [comment]
One last thing. The makeImage function was updated last month by @ncullen.
Not sure what he did there but there is also a chance something changed
there. We may need to dig up if the new changes cause that, and the best
way would be to install an earlier version of Anëtar or use the docker
container that was built some long time ago. I can point you to it if you
know how to run containers.

**Comment by yizhwan** [comment]
Thanks for the suggestions. I tried running regres with the same output. I have not loaded any other libraries.
I have also tried giving it a preloaded binary brain mask, which then gives me the following error when running regressfast:

warning: solve(): system is singular; attempting approx solution
Error: inv(): matrix is singular

I have 50 pts with binary tumour masks and my dependent variable is a varimax rotated PCA component score from a cognitive battery. 

I wonder in this circumstance, if this is an issue with perfect fit, should I try running a PCA on the voxel data before running lesymap? I have noticed that in your previous papers and Chris Sperber's work similar methods have been used.

**Comment by dorianps** [comment]
If boxes are binary, why do you use regression? You can use t-tests for
mass univariate analysis, Brunner munzel tests, or use sccan for
multivariate. It may also be good to increase the minimum number of
affected subjects to 8-9-10. Having 5 subjects lesioned in a single voxel
is not much, and maybe the singular solution may be because you are
comparing 5 vs 45 subjects in some voxels where there is not enough
variance in your PCA component for each group to make the comparison.

**Comment by dorianps** [comment]
Did you manage to fix this?

**Comment by yizhwan** [comment]
Thanks for the suggestions. I can confirm that I have re-run the scripts with Docker and it works with both the linear regression and BM tests. So it does seem to be an issue with the makeImage function.

**Comment by dorianps** [comment]
@ncullen93 Do you know if any of the changes you made last month can explain this issue:

Commit history:
https://github.com/ANTsX/ANTsR/commits/master/R/makeImage.R

**Comment by dorianps** [comment]
@yizhwan can you paste the log when you run it with the docker containers. I can understand makeImage stumbling on something, but the inability to solve the equation is not related to ANTsR, so I want to check if you see the same warnings still.

**Comment by ncullen93** [comment]
Hm yes definitely possible. That error suggests that the `voxval` argument doesn't exist in the function. There are now two `makeImage` functions - one in ANTsRCore that calls the underlying C++ code and should never be called by a user, and one in ANTsR that calls that ANTsRCore version of the makeImage function under the hood and should be used by users.

I'm thinking that the `makeImage` function there is getting picked up by ANTsRCore instead of ANTsR. Basically, ANTsRCore should not be loaded or called. The best fix would be to add `ANTsR::` to all function calls to ensure the right version is getting called. The easiest fix might be to just remove ANTsRCore as a dependency or any `library(ANTsRCore)` calls because it should never be used directly anymore. The other fix would be to ensure you install an old ANTsR / ANTsRCore version.

Apologies for the inconvenience but this was a very necessary long-term improvement for ANTs - to know that all user-related functions are coming from ANTsR. The functionality should not have changed though.

**Comment by dorianps** [comment]
Thanks @ncullen93 . Should remove the ANTsRCore import line here: https://github.com/dorianps/LESYMAP/blob/master/DESCRIPTION#L19

@yizhwan can you run `?makeImage` and see in the help it appears which package it is coming from, ANTsR or ANTsRCore?

**Comment by ncullen93** [comment]
Yes I think that would work. You shouldn't have ANTsRCore as a dependency. It will just get installed with ANTsR but your library shouldn't have it in the namespace.

**Comment by dorianps** [comment]
@yizhwan I updated LESYMAP to hopefully avoid the makeImage issue. Do you have a chance to reinstall LESYMAP and try your analysis again?

**Comment by yizhwan** [comment]
Apologies for the late reply. I have reinstalled LESYMAP and ANTSR and unfortunately the error is is the same. EVerything is working fine via Docker so I am continuing my analysis using that for now. Thanks!

**Comment by dorianps** [comment]
Ok, thanks for trying.

**Comment by dorianps** [comment]
@yizhwan I put some minor fixes to avoid the issue. I cannot check if your issue is resolved because I don't have your data, but if you can reinstall everything again and try, that would be helpful. It will work only if you remove and install again ITKR, ANTsRCore, ANTsR, LESYMAP. It is fine if you don't have time to do this, I understand.

**Comment by dorianps** [comment]
Issue should be resolved now with the fixes in ANTsR and LESYMAP.
