### ISSUE TITLE
Error in antsImageRead(lesions.list[1]): argument "r_pixeltype" is missing, with no default

### ISSUE THREAD

**Issue by Frozen0w0** [dorianps/LESYMAP#41]
Hello team, 
Thank you so much for sharing the code! I encountered a small problem during the execution and hope to get your guidance.

While testing "example (lesymap)," I encountered an error:

22:20:40 Running LESYMAP 0.0.0.9221
22:20:40 Checking afew things...
22:20:40 Loading behavioral data...131 scores found.
22:20:40 Filenames as input,checking lesion values on ist image...
Error in antsImageRead(lesions.list[1]):
argument "r_pixeltype" is missing, with no default

However, when I run the command "antsImageRead(lesions.list[1])" individually, there is no problem: 

>antsImageRead(lesions.list[1])
antsImage
Pixel Type                    :float
Components Per Pixel :1
Dimensions                 :181x217x181
Voxel spacing              :1x1x1.
Origin                          :90 125 -71
Direction                      :-1 0  0 0 -1 0 0 0 1
Filename                      :/usr/local/lib/R/site-library/LESMAP/extdata/lesions/Subject_001.nii.gz

Do you know how to solve this problem? Looking forward to your reply, thank you!!!

**Comment by dorianps** [comment]
If the error is on the example as you say, the problem is a recent refactoring of the ANTsR software which apparently has broken a bunch of functions. I will need to update lesymap for a permanent solution. At the moment you have two options:

1. Use the Docker container which worked also for someone else that had a problem recently. The latest container was built years ago but nothing has changed in Lesymap anyway.

2. Manually install an older version of ANTsR from 6+ months ago. Then install only lesymap but pay attention that it does not update ANTsR in the process.

Pinging @ncullen93 . Nick, looks like refactoring has caused other issues with antsimageread this time.

**Comment by ncullen93** [comment]
Same issue as before - you're importing ANTsRCore functions into the environment when they shouldn't be there. Did you remove ANTsRCore as a dependency? 

The issue is not helped by the fact that there is an `antsImageRead` function in both ANTsR (that users should call) and ANTsRCore (that users should not call because it is called internally by the ANTsR function). I will rename those internal functions so they don't conflict.

**Comment by ncullen93** [comment]
Sorry @dorianps I think I realize the issue now on our side and have fixed it. It shouldn't be a problem anymore as long as ANTsRCore is not a dependency.

**Comment by dorianps** [comment]
@ncullen93 thank you. I put a fresh install of LESYMAP and all seems to work. I managed to eliminate the function conflicts by removing any import of ANTsRCore.

@Frozen0w0  Can you uninstall and install again all four software (ITKR, ANTsRCore, ANTsR, LESYMAP)? This should resolve your issue. Let me know if it works so I can bump the LESYMAP version.

**Comment by Frozen0w0** [comment]
Thank you very much for the replies and guidance!! After I uninstalled and re-installed these four software, all programs worked normally!  :）

**Comment by dorianps** [comment]
Thanks for confirming @Frozen0w0 .

Thanks for fixing ANTsR @ncullen93 .

I am bumping the lesymap version. Issue closed.
